<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
</head>
<body>
	<div id="custom-header"></div>
	<div class="wrap">
		<?php echo $this->render('_header2.phtml')?>
		<?php echo $this->layout()->content;?>
		<?php echo $this->render('_footer.phtml')?>
	</div>
</body>
</html>
