<?php echo $this->doctype() ?>

<html xml:lang="zh-CN" xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headStyle() ?>
    <?php echo $this->headLink() ?>    
</head>
<body>
	<div id="custom-header"></div>
	<div class="wrap">
		<?php echo $this->render('_header.phtml')?>
		<?php echo $this->layout()->content;?>
		<?php echo $this->render('_footer.phtml')?>
	</div>
	<?php $this->addJavascript('jquery/jquery-1.6.4.min.js','first') ?>	
    <?php echo $this->headScript(); ?>
</body>
</html>
