<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->addJavascript('fancybox/jquery.mousewheel-3.0.4.pack.js','first'); ?>
<?php echo $this->addJavascript('fancybox/jquery.fancybox-1.3.4.pack.js','first'); ?>
<?php echo $this->addJavascript('jquery/jquery-1.7.2.min.js','first'); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/js/fancybox/jquery.fancybox-1.3.4.css'); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>
</head>
<body>
	<div id="custom-header"></div>
	<div class="wrap">
		<?php echo $this->render('_header.phtml')?>
		<?php echo $this->layout()->content;?>
		<?php echo $this->render('_footer.phtml')?>
	</div>
    <?php echo $this->headScript(); ?>        
</body>
</html>
