<div class="col2-layout">
    <div class="col-left">
        <!-- 问题列表begin -->
        <div class="title_v">
            <h3><?php echo $this->catSelected['title'] ?></h3>
            <ul class="tags">
                <li <?php echo ('unsolve' == $this->questionTab ) ? 'class="sel"' : '' ?>>
                    <?php echo $this->linkTo('待解决的问题', '@catalogQuestion?catalog='.$this->selCatId.'&show=unsolve') ?></li>
                <li <?php echo ('solve' == $this->questionTab ) ? 'class="sel"' : '' ?>>
                    <?php echo $this->linkTo('已解决的问题', '@catalogQuestion?catalog='.$this->selCatId.'&show=solve') ?></li>
                <li <?php echo ('zero' == $this->questionTab ) ? 'class="sel"' : '' ?>>
                    <?php echo $this->linkTo('无回答的问题', '@catalogQuestion?catalog='.$this->selCatId.'&show=zero') ?></li>
            </ul>
            <div class="clearfix"></div>
        </div>           
        <?php echo $this->render('partial/_questionTab.phtml'); ?>
        <!-- 问题列表end -->
    </div>
    <div class="col-right">
        <?php echo $this->render('partial/_search.phtml') ?>
        <!-- 热门标签begin -->
        <div id='popular-tags' class="mt20">
            <strong><a href="/question/tags?catalog=1" class='more'>所有标签&raquo;</a>热门标签</strong>
            <div>
                <?php foreach($this->hotKeywords as $keyword) :?>
                    <a href="<?php echo $this->urlFor('@tagQuestion?tagname=' . urlencode($keyword['word'])) ?>" class='tag project'><?php echo $keyword['word'] . '<em>('. $keyword['scores'].'</em>'?>)</a>
                <?php endforeach ?>
            </div>
        </div>
        <!-- 热门标签end -->
        <!-- 活跃会员begin -->
        <div id='top-users' class="mt20">
            <strong>活跃会员(TOP <?php echo count($this->topUsers)?>)</strong>
            <ul>
                <?php foreach($this->topUsers as $user) :?>
                <li>
                    <?php echo $this->face($user['user_logo'],$user['user_id']) ?>
                    <p><?php echo $this->linkTo($user['user_name'],'@userHome?id='.$user['user_id']) ?></p>
                </li>
                <?php endforeach;?>
            </ul>
        </div>
        <!-- 活跃会员end -->
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
