<div class="path-info"><?php echo $this->breadcrumb('搜索结果'); ?></div>
<div id="search-sort" class="heading-tabs">
	<span class="active"><a href="#">讨论区</a></span>
	<span class="sort-method">
		按 <a class="sel" href="?scope=bbs&amp;q=php&amp;lang=0">默认</a> |
    	<a href="?scope=bbs&amp;q=php&amp;lang=0&amp;sort=time">时间</a>
    	对搜索结果排序
     </span>
</div>
<div class="col2-layout">
	<div class="col-left">
		<div class="search-results">
		    <?php foreach ($this->results as $row) :?>
			<dl>
				<dd><h4><?php echo $this->linkTo($this->substr($row['subject'],50), '@showQuestion?token='.$row['token'], 'target=_blank class=thread') ?>
						<span class="stat">(<?php echo $row['user_name'] . ' 更新于 ' . $this->timing($row['created_at'])?>)</span>
					</h4>
					<p class="detail">
					    <?php echo $this->substr($row['content'],120) ?>
					    <?php echo $this->linkTo('查看全文', '@showQuestion?token='.$row['token'], 'target=_blank')?>
					</p>			
				</dd>
				<dt><?php echo $this->face($row['user_logo'],$row['user_id']); ?></dt>
				<div class="clearfix"></div>				    
			</dl>
			<?php endforeach; ?>
		</div>		
	</div>
	<div class="col-right">
		sdfsd
	</div>
</div>