<?php echo $this->render('partial/_path.phtml') ?>
<div class="asked-tip">
    <h1><em>“<?php echo $this->question['subject'] ?>”</em>提交成功！</h1>
    <div class="text">提问和发帖注意事项：
        <ul>
            <li>必须在1个小时内而且没人回复的情况下才能修改和删除问题</li>
            <li>问题补充：对提问进行补充，以得到更准确的答案</li>
            <li>为鼓励好答案，请为他们投票并设置最佳答案（仅限提问）</li>
        </ul>
    </div>
    <a href="<?php echo $this->urlFor('@showQuestion?token='.$this->question['token'])?>" class="rndbutton btn_view"><span>查看我的问题</span></a>
    <div class="clearfix"></div>
</div>