<div class="col2-layout">
    <div class="col-left">
        <!-- 问题列表begin -->
        <div class="title_v">
            <h3>标签 » <?php echo $this->tagname ?></h3>
            <ul class="tags">
                <li <?php echo ('unsolve' == $this->questionTab ) ? 'class="sel"' : '' ?>>
                    <a href="?show=unsolve">待解决的问题</a>
                </li>    
                <li <?php echo ('solve' == $this->questionTab ) ? 'class="sel"' : '' ?>>
                    <a href="?show=solve">已解决的问题</a>
                </li>    
                <li <?php echo ('zero' == $this->questionTab ) ? 'class="sel"' : '' ?>>
                    <a href="?show=zero">无回答的问题</a>        
                </li>    
            </ul>
            <div class="clearfix"></div>
        </div>         
        <?php echo $this->render('partial/_questionTab.phtml'); ?>
        <!-- 问题列表end -->
    </div>
    <div class="col-right">
        right
    </div>
</div>    