<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/fancybox/jquery.fancybox-1.3.4.css') ?>
<?php $this->addJavascript('fancybox/jquery.fancybox-1.3.4.pack.js'); ?>
<?php $this->addJavascript('wenda/qcontent.js');?>
<div class="col2-layout">
	<div class="col-left path-info"><?php echo $this->breadcrumb($this->substr($this->question['subject'],30)); ?></div>
	<div class="col-right"><?php echo $this->render('partial/_search.phtml');?></div>
	<div class="clearfix"></div>
</div>
<div id="question" class="col2-layout">
	<!-- 问题标题begin -->
	<div class="title">
		<div class="asker">
		    <?php echo $this->face($this->question['user_logo'],$this->question['user_id']) ?>
		</div>
		<div class="qtitle">
            <h1><?php echo $this->escape($this->question['subject']) ?></h1>
			<div class="stat">
			    <?php echo $this->linkTo($this->question['user_name'],'@userHome?id='.$this->question['user_id'], 'target=_blank')?>
				发表于 <?php echo date('m-d h:i',$this->question['created_at']) . '&nbsp;&nbsp;'.$this->timing($this->question['created_at'])?>
                <?php printf('%d回/%d阅', $this->question['answers'],$this->question['pageviews']) ?>
                <?php if (!empty($this->question['last_answer_at'])) printf('，最后回答: %s分钟前', $this->timing($this->question['last_answer_at'])) ?>
                (<em id="p_attention_count"><?php echo $this->question['collects']?></em>人收藏
				<span id="attention_it">，<a href="#" onclick="add_to_favorite(37137,true);return false;">收藏</a></span>|
				<a href="#">举报</a>)
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<!-- 问题标题end -->
	<div class="col-left">
		<!-- 问题主体begin -->
		<div class="body">
			<div class="vote">
				<a id="vote_up" class="vote-up-off" href="#" title="顶：这问题很有用或者很提问清晰明了">顶</a>
				<span class="vote-count-post"><?php echo $this->question['votes']?></span>
				<a id="vote_down" class="vote-down-off" href="#" title="踩：这问题不知道在问什么，或者没什么用">踩</a>
				<div class="clearfix"></div>
			</div>
			<div class="content">
				<p><?php echo $this->stripScript($this->question['content']) ?></p>
				<div class="Tags mt10">
					<strong>标签：</strong>
    			    <?php $this->showTags($this->question['keywords']); ?>
			    </div>
			</div>
			<div class="clearfix"></div>
		</div>
		<!-- 问题的主体end -->
		<!-- 回复列表begin -->
		<div class="answers">
        	<div class="title">
				<span>
					<a class="current" href="#">按评价排序</a> |
					<a href="#">显示最新答案</a> |
					<a href="#top">回页面顶部</a>
				</span>
				<a name="answers"></a>
                <h2>共有<em class="count"><?php echo $this->question['answers']?></em>个答案 <a class="answer" href="#answer_form">我要回答»</a></h2>
			</div>
			<ul class="list">
                <?php if (!empty($this->answers)) : ?>
                <?php foreach ($this->answers as $answer) :?>
				<li>
					<div class="user">
                         <?php echo $this->face($answer['user_logo'],$answer['user_id']) ?>                        
					</div>
					<div class="content">
                        <div>
                            <div class="time"><?php printf('%s 回答于 %s (%s)', $answer['user_name'], date('m-d h:i',$answer['created_at']) , $this->timing($answer['created_at']) )?></div>
                            <div class="opts"><a href="#">举报</a></div>
    						<div class="clearfix"></div>
                        </div>    
						<div class="detail"><?php echo $this->stripScript($answer['content']) ?></div>
                        <div id="post_answer_<?php echo $answer['id']?>" class="replies">
                            <?php echo (isset($answer['replies'])) ? $this->replies($answer['replies']):'' ?>
                        </div>
						<div class="votes">
						    <a href="<?php printf("javascript:reply_to_post('%s')", $this->urlFor("ajax/reply?postid=" . $answer['id']) ) ?>">评论</a><em>(<?php echo isset($answer['replies']) ? count($answer['replies']) : 0 ;?>)</em> |
					    	<a href="#">引用此答案</a>
					    </div>
					</div>
					<div class="clearfix"></div>
				</li>
                <?php endforeach; ?>
                <?php endif; ?>
			</ul>
            <div class="mtb10">
                <?php if($this->answersPaginator instanceof Zend_Paginator): ?>
                    <?php echo $this->paginationControl($this->answersPaginator,'Sliding','partial/_paginator.phtml'); ?>
                <?php endif ?>                  
            </div>                   
		</div>
		<!-- 回复列表end -->
		<!-- 回复Form begin -->
		<div class="answer-form">
			<div class="user">
                <?php echo $this->face(); ?>
			</div>
			<form method="post" action="answer" id="answer_form">
			    <input type="hidden" value="<?php echo $this->question['id'] ?>" id="question_id" name="question_id" />
			    <input type="hidden" value="<?php echo $this->question['token']?>" id="token" name="token" />
				<textarea id="content" name="content" class="content"><?php echo $this->postData['content']?></textarea><br />
                <?php if ($this->authInfo()->isLogined()) :?>
                    <input type="submit" id="submit" name="submit" value=" 我要回答 "/>
                <?php else : ?>
                    <input type="submit" id="submit" name="submit" value=" 我要回答 " disabled/>
                                        用户尚未登录，点击<?php echo $this->linkTo('这里','customer/login') ?>登录
                <?php endif ?>
                <?php echo $this->showErrors($this->errorMsg) ?>
				<br/><br/>
				<a href="#answers">回答案顶部</a> | <a href="#top">回页面顶部</a>
			</form>
			<div class="clearfix"></div>
		</div>
		<!-- 回复Form end -->
	</div>
	<div class="col-right">
		<!-- 用户的其它问题begin -->
		<div class="other-qlist">
			<strong>
                <?php echo $this->linkTo('全部...','@userHome?id='.$this->question['user_id'],'class=more') ?><em><?php echo $this->question['user_name']?>*</em>的其他问题</strong>
			<ul>
				<?php foreach($this->askedQuestions as $question) :?>
                    <li>
                        <?php echo $this->linkTo($this->escape($question['subject']), '@showQuestion?token='.$question['token'], 'target=_blank') ?>
                        <span class="date"><?php printf('(%d回/%d阅,%s)',$question['answers'],$question['pageviews'],$this->timing($question['created_at']))?></span>
                    </li>
                <?php endforeach ?>
			</ul>
		</div>
		<!-- 用户的其它问题end -->
        <!-- 类似的问题start -->
		<div class="other-qlist">
			<strong>类似的话题</strong>
			<ul>
                <?php foreach($this->otherQuestions as $question) : ?>
                    <li>
                        <?php echo $this->linkTo($this->escape($question['subject']), '@showQuestion?token='.$question['token'], 'target=_blank') ?>
                        <span class="date"><?php printf('(%d回/%d阅,%s)',$question['answers'],$question['pageviews'],$this->timing($question['created_at']))?></span>
                    </li>
                <?php endforeach; ?>
			</ul>
		</div>
        <!--类似的问题-->
	</div>
	<div class="clearfix"></div>
</div>