<div class="question-list">
    <div class="mtb10">
        <?php if($this->questions instanceof Zend_Paginator): ?>
            <?php echo $this->paginationControl($this->questions,'Sliding','partial/_paginator.phtml'); ?>
        <?php endif ?>                
    </div>
    <ul>
        <?php foreach ($this->questions as $question) : ?>
            <li class="question">
                <?php echo $this->face($question['user_logo'],$question['user_id']); ?>
                <div class="qbody">
                    <h2><?php echo $this->linkTo($question['subject'], '@showQuestion?token='.$question['token'], 'target=_blank') ?></h2>
                    <div class="tags">
                        <?php $this->showTags($question['keywords']); ?>
                    </div>
                    <div class="date">
                        <?php echo $question['user_name'] . ' 发布于 ' . $this->timing($question['created_at'])?>
                        <?php if ($question['last_answer_at'] > 0) echo '，最后回答('.$this->timing($question['last_answer_at']).')：'.'<a href="http://www.oschina.net/question/28_37571?sort=time#answers">'.$question['last_answer_user_name'].'</a>'?>
                    </div>
                </div>
                <div class="qstat">
                    <a href="<?php echo $this->urlFor('@showQuestion?token='.$question['token']) ?>">
                        <ul>
                            <li class="answer"><em><?php echo $question['answers'] ?></em>回答</li>
                            <li class="vote"><em><?php echo $question['votes'] ?></em>投票</li>
                            <li class="view"><em><?php echo $question['pageviews'] ?></em>浏览
                            </li>
                        </ul></a>
                </div>
                <div class="clearfix"></div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<div>
    <a class="fr" href="#">返回列表顶部</a>
    <div class="mtb10">
        <?php if($this->questions instanceof Zend_Paginator): ?>
            <?php echo $this->paginationControl($this->questions,'Sliding','partial/_paginator.phtml'); ?>
        <?php endif ?>                  
    </div>
</div>